#include "planificador_corto_plazo.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <commons/log.h>
#include <utils/utils.h>
#include <pthread.h>
#include <semaphore.h>
#include <main.h>
#include <pcb.h>